# Generated by Django 5.1.2 on 2024-11-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_db',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipeno', models.IntegerField(default=0)),
                ('recipename', models.CharField(max_length=255)),
                ('mixingspeed', models.FloatField()),
                ('mixingtemp', models.FloatField()),
                ('mixingtime', models.IntegerField()),
            ],
            options={
                'db_table': 'tblrecipe',
            },
        ),
    ]
